### ISSUE TITLE
Clean the spreadsheet

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/plot_the_dots#9]
The app should provide some basic tools to deal with ugly spreadsheets- e.g. reading the headers from rows other than row 1, maybe even cleaning up spaces a bit

**Comment by tomjemmett** [comment]
duplicate of #6: I think we shouldn't be too ambitious with cleaning the data. I think the app should aim to produce SPC charts and that's it (keeps the project simpler for us!) but we may want to review this overtime.
